# Generated by Django 5.2.1 on 2025-07-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notificationusermodel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='request_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='response_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
