# Generated by Django 5.2.1 on 2025-06-20 20:08

import django.db.models.deletion
import project_app.models
import project_app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department_app', '0001_initial'),
        ('organization_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('image', models.FileField(blank=True, upload_to='project_images/%Y/%m/')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('location_address', models.CharField(blank=True, max_length=255, null=True)),
                ('map_location_link', models.URLField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Upcoming'), (2, 'Pending'), (3, 'In progress'), (4, 'Cancelled'), (5, 'On Hold'), (6, 'Completed')], default=1)),
                ('total_unused_kg', models.FloatField(default=0)),
                ('total_kg', models.FloatField(default=0)),
                ('total_project_progress', models.FloatField(default=0)),
                ('total_clerk_progress_percentage', models.FloatField(default=0)),
                ('total_shop_progress_percentage', models.FloatField(default=0)),
                ('total_cut_progress_percentage', models.FloatField(default=0)),
                ('total_fit_progress_percentage', models.FloatField(default=0)),
                ('total_delivery_progress_percentage', models.FloatField(default=0)),
                ('total_received_progress_percentage', models.FloatField(default=0)),
                ('total_erect_progress_percentage', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization_app.organizationmodel')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectGalleryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to=project_app.utils.project_gallery_upload_path)),
                ('caption', models.TextField(blank=True, null=True)),
                ('organise_type', models.IntegerField(choices=[(1, 'Completed'), (2, 'Delivered'), (3, 'Issues')], default=project_app.models.OrganiseType['COMPLETED'])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_galleries', to='project_app.projectmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_first_name', models.CharField(max_length=100)),
                ('user_id_value', models.CharField(max_length=100)),
                ('user_mobile', models.CharField(max_length=15)),
                ('user_email', models.EmailField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ProjectUsersDepartment', to='department_app.departmentmodel')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_users', to='organization_app.organizationmodel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_projects', to='project_app.projectmodel')),
            ],
            options={
                'verbose_name': 'Project User',
                'verbose_name_plural': 'Project Users',
            },
        ),
    ]
