# Generated by Django 5.2.1 on 2025-06-20 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectusermodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='projectusermodel',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='unique_project_user'),
        ),
    ]
