# Generated by Django 5.2.1 on 2025-07-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
