# Generated by Django 5.2.1 on 2025-11-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0004_alter_projectmodel_end_date_alter_projectmodel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='employee_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
