# Generated by Django 5.2.1 on 2025-11-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0005_projecttask_employee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='total_delivery_3p_progress_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='total_weld_progress_percentage',
            field=models.FloatField(default=0),
        ),
    ]
