"""
Django settings for jaysmetal_backend project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config
import sentry_sdk
from sentry_sdk.integrations.logging import LoggingIntegration
from sentry_sdk.integrations.django import DjangoIntegration
import logging


# DEFAULT_FILE_STORAGE = 'jaysmetal_backend.storage_backends.MediaStorage'
# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', cast=bool)

ALLOWED_HOSTS = ['*']
# ALLOWED_HOSTS = ['15.223.6.59','sandbox.jaysmetal.com', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'storages',
    
    # Installed apps
    'user_app',
    'core_app',
    'organization_app',
    'department_app',
    'project_app',
    'fablist_app',
    'notification_app',
    'settings_app',
    'reports_app',
    'crm_app.structural',
    'crm_app.architectural',
    'crm_app.leads',
    
    
    # Third party apps
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
]


#AWS S3 STORAGE BUCKET SETTINGS
# INSTALLED_APPS.append('storages') 


# AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')
# AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME')
# AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
# # AWS_DEFAULT_ACL = 'public-read'
# # Additional configurations for S3
# AWS_S3_FILE_OVERWRITE = False
# AWS_DEFAULT_ACL = None
# # AWS_S3_SIGNATURE_VERSION = 's3v4'

# AWS_ACCESS_KEY_ID = config('S3_BUCKET_ACCESS_KEY_ID')
# AWS_SECRET_ACCESS_KEY = config('S3_BUCKET_SECRET_ACCESS_KEY')


# Media files
# MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
# MEDIA_URL = 'media/'

# STORAGES = {

#     # Media file (image) management  
#     "default": {
#         "BACKEND": "storages.backends.s3boto3.S3StaticStorage",
#     },
    
#         # CSS and JS file management
#     "staticfiles": {
#         "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
#     },
   
   
# }


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ORIGIN_ALLOW_ALL = True
CSRF_TRUSTED_ORIGINS = [
    "https://sandbox.jaysmetal.com",
    "https://live.jaysmetal.com",
    "https://localhost",
    "https://35.183.71.63",
#     "http://localhost:8000",
    "http://localhost:3000",
#     "http://127.0.0.1:8000"
    
]

ROOT_URLCONF = 'jaysmetal_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jaysmetal_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('POSTGRES_DB'),
        'USER': config('POSTGRES_USER'),
        'PASSWORD': config('POSTGRES_PASSWORD'),
        'HOST': config('POSTGRES_HOST', default='127.0.0.1'),
        # 'HOST': '127.0.0.1', 
        'PORT': config('POSTGRES_PORT', default='5432'),
    }
}


# print("ENV FILE:", os.path.exists('.env'))  # True means it's in the right place
# print("POSTGRES_HOST from config:", config('POSTGRES_HOST', default='MISSING'))
# print("Database ",DATABASES)
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = 'static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Set custom user model
AUTH_USER_MODEL = 'user_app.UserDetail'

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://redis:6379/0",  # Matches compose service name
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "root": {
        "level": "WARNING",
        "handlers": ["console", "sentry"],
    },
    "formatters": {
        "verbose": {
            "format": "%(levelname)s %(asctime)s %(module)s %(message)s"
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "sentry": {
            "level": "ERROR",
            "class": "sentry_sdk.integrations.logging.EventHandler",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "sentry"],
            "level": "ERROR",
            "propagate": True,
        },
        "django.server": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },

}



# Sentry settings
# sentry_logging = LoggingIntegration(
#     level=None,                # Capture all levels
#     event_level=logging.ERROR  # Send events to Sentry on ERROR or higher
# )

# sentry_sdk.init(
#     dsn=config('SENTRY_DNS'),
#     # Add data like request headers and IP for users,
#     # see https://docs.sentry.io/platforms/python/data-management/data-collected/ for more info
#     integrations=[DjangoIntegration(), sentry_logging],
#     traces_sample_rate=1.0,
#     send_default_pii=True
# )

REST_FRAMEWORK = {
    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'DEFAULT_PAGINATION_CLASS': 'django_solvitize.utils.custompagination.CustomPagination',   
    'PAGE_SIZE': 8,
}


# AMAZON SES
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'email-smtp.ca-central-1.amazonaws.com'  # e.g., email-smtp.us-east-1.amazonaws.com
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'AKIAQEKJK4YQTMQI3ZN7'  # From SMTP credentials
EMAIL_HOST_PASSWORD = 'BCQ8beIxt7/oDGd3+Jy16BeKLDKUp4UU61WYKSdGCsOA'  # From SMTP credentials
DEFAULT_FROM_EMAIL = "Jays Metal <no-reply@jaysmetal.com>"

# CELERY SETTINGS
CELERY_BROKER_URL = config("CELERY_BROKER_URL", "redis://redis:6379/0")
CELERY_RESULT_BACKEND = CELERY_BROKER_URL

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
