# Generated by Django 5.2.1 on 2025-11-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentmodel',
            name='name',
            field=models.CharField(choices=[('clerk', 'clerk'), ('shop', 'shop'), ('cut', 'cut'), ('fit', 'fit'), ('delivery', 'delivery'), ('received', 'received'), ('erect', 'erect'), ('weld', 'weld'), ('delivery 3p', 'delivery 3p')], max_length=100, unique=True),
        ),
    ]
