# Generated by Django 5.2.1 on 2025-06-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='is_dev',
            field=models.BooleanField(default=False),
        ),
    ]
