# Generated by Django 5.2.1 on 2025-07-31 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_userdetail_is_dev'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
