# Generated by Django 5.2.1 on 2025-11-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department_app', '0002_alter_departmentmodel_name'),
        ('user_app', '0003_userdetail_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('permissions', models.JSONField()),
                ('access_details', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='userdetail',
            name='user_departments',
            field=models.ManyToManyField(blank=True, related_name='user_departments', to='department_app.departmentmodel'),
        ),
    ]
