# Generated by Django 5.2.1 on 2025-12-13 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_roles_userdetail_user_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_roles_reference', to='user_app.roles'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='security_key',
            field=models.CharField(blank=True, db_index=True, max_length=6, null=True),
        ),
    ]
