# Generated by Django 5.2.1 on 2025-12-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structural', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structuralcompany',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='structuralcompany',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
