# Generated by Django 5.2.1 on 2025-12-25 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structural', '0003_alter_structuralcompany_added_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='structuralcalendaractivity',
            name='related_reminder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='structural.structuralreminder'),
        ),
        migrations.AddField(
            model_name='structuralcalendaractivity',
            name='title',
            field=models.CharField(default='Untitled Activity', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StructuralNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='structural.structuralcompany')),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='structural.structuralreminder')),
                ('sales_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
