# Generated by Django 5.2.1 on 2025-12-29 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structural', '0004_structuralcalendaractivity_related_reminder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='structuralreminder',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StructuralCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('company_type', models.CharField(choices=[('Existing', 'Existing'), ('Potential', 'Potential')], max_length=20)),
                ('existing_category', models.CharField(blank=True, choices=[('GC', 'GC'), ('Builder', 'Builder'), ('Architect', 'Architect')], max_length=20, null=True)),
                ('potential_category', models.CharField(blank=True, choices=[('GC', 'GC'), ('Builder', 'Builder'), ('Architect', 'Architect')], max_length=20, null=True)),
                ('lead_status', models.CharField(blank=True, choices=[('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold')], max_length=10, null=True)),
                ('project_status', models.CharField(blank=True, choices=[('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='structural_companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='structuralcalendaractivity',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_activities', to='structural.structuralcustomer'),
        ),
        migrations.AlterField(
            model_name='structuralcontact',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='structural.structuralcustomer'),
        ),
        migrations.AlterField(
            model_name='structuralnote',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='structural.structuralcustomer'),
        ),
        migrations.AlterField(
            model_name='structuralnotification',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='structural.structuralcustomer'),
        ),
        migrations.AlterField(
            model_name='structuralproject',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='structural.structuralcustomer'),
        ),
        migrations.AlterField(
            model_name='structuralreminder',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='structural.structuralcustomer'),
        ),
        migrations.DeleteModel(
            name='StructuralCompany',
        ),
    ]
