# Generated by Django 5.2.1 on 2025-12-30 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structural', '0005_alter_structuralreminder_note_structuralcustomer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structuralreminder',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='structuralreminder',
            name='note',
        ),
        migrations.AddField(
            model_name='structuralreminder',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structuralreminder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-12-30 17:31:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='structuralreminder',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='structural.structuralproject'),
        ),
        migrations.AddField(
            model_name='structuralreminder',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='Scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='structuralreminder',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='structuralreminder',
            name='frequency',
            field=models.CharField(choices=[('None', 'None'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly'), ('Custom', 'Custom')], max_length=20),
        ),
    ]
