# Generated by Django 5.2.1 on 2025-12-30 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structural', '0006_remove_structuralreminder_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structuralcustomer',
            old_name='company_type',
            new_name='category',
        ),
    ]
