# Generated by Django 5.2.1 on 2025-06-20 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricationStatusModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_first_name', models.CharField(max_length=100)),
                ('user_id_value', models.CharField(max_length=100)),
                ('user_mobile', models.CharField(max_length=15)),
                ('user_email', models.EmailField(max_length=100)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fabrication Status',
                'verbose_name_plural': 'Fabrication Status',
            },
        ),
        migrations.CreateModel(
            name='FabricationListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('profile', models.CharField(blank=True, max_length=255)),
                ('qty', models.IntegerField()),
                ('kg', models.FloatField()),
                ('total_kg', models.FloatField(default=0)),
                ('total_progress', models.FloatField(default=0)),
                ('clerk_progress_percentage', models.FloatField(default=0)),
                ('shop_progress_percentage', models.FloatField(default=0)),
                ('cut_progress_percentage', models.FloatField(default=0)),
                ('fit_progress_percentage', models.FloatField(default=0)),
                ('delivery_progress_percentage', models.FloatField(default=0)),
                ('received_progress_percentage', models.FloatField(default=0)),
                ('erect_progress_percentage', models.FloatField(default=0)),
                ('clerk_status', models.BooleanField(default=False)),
                ('shop_status', models.BooleanField(default=False)),
                ('cut_status', models.BooleanField(default=False)),
                ('fit_status', models.BooleanField(default=False)),
                ('delivery_status', models.BooleanField(default=False)),
                ('received_status', models.BooleanField(default=False)),
                ('erect_status', models.BooleanField(default=False)),
                ('clerk_completed_at', models.DateTimeField(blank=True, null=True)),
                ('shop_completed_at', models.DateTimeField(blank=True, null=True)),
                ('cut_completed_at', models.DateTimeField(blank=True, null=True)),
                ('fit_completed_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_completed_at', models.DateTimeField(blank=True, null=True)),
                ('received_completed_at', models.DateTimeField(blank=True, null=True)),
                ('erect_completed_at', models.DateTimeField(blank=True, null=True)),
                ('incomplete_departments', models.JSONField(blank=True, default=dict, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fablist_organization', to='organization_app.organizationmodel')),
            ],
            options={
                'verbose_name': 'Fabrication List',
                'verbose_name_plural': 'Fabrication Lists',
            },
        ),
    ]
