# Generated by Django 5.2.1 on 2025-06-20 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department_app', '0001_initial'),
        ('fablist_app', '0001_initial'),
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricationlistmodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fablist_project', to='project_app.projectmodel'),
        ),
        migrations.AddField(
            model_name='fabricationstatusmodel',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fabricationstatus_department', to='department_app.departmentmodel'),
        ),
        migrations.AddField(
            model_name='fabricationstatusmodel',
            name='fabrication_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='fablist_app.fabricationlistmodel'),
        ),
    ]
