# Generated by Django 5.2.1 on 2025-07-14 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fablist_app', '0003_initial'),
        ('project_app', '0003_alter_projectmodel_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricationlistmodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fablist_project', to='project_app.projectmodel'),
        ),
        migrations.AlterField(
            model_name='fabricationstatusmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fabricationstatus_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
