# Generated by Django 5.2.1 on 2025-09-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fablist_app', '0004_alter_fabricationlistmodel_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricationlistmodel',
            name='delivery_3p_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fabricationlistmodel',
            name='delivery_3p_progress_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fabricationlistmodel',
            name='delivery_3p_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fabricationlistmodel',
            name='weld_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fabricationlistmodel',
            name='weld_progress_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fabricationlistmodel',
            name='weld_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fabricationlistmodel',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
