# Generated by Django 5.2.1 on 2025-11-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fablist_app', '0005_fabricationlistmodel_delivery_3p_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricationlistmodel',
            name='clerk_completion_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fabricationlistmodel',
            name='cut_completion_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fabricationlistmodel',
            name='delivery_3p_completion_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fabricationlistmodel',
            name='delivery_completion_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fabricationlistmodel',
            name='erect_completion_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fabricationlistmodel',
            name='fit_completion_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fabricationlistmodel',
            name='received_completion_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fabricationlistmodel',
            name='shop_completion_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fabricationlistmodel',
            name='weld_completion_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
