# Generated by Django 5.2.1 on 2025-11-14 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fablist_app', '0006_fabricationlistmodel_clerk_completion_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricationlistmodel',
            name='clerk_completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clerk_completed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fabricationlistmodel',
            name='cut_completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cut_completed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fabricationlistmodel',
            name='delivery_3p_completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_3p_completed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fabricationlistmodel',
            name='delivery_completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_completed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fabricationlistmodel',
            name='erect_completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erect_completed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fabricationlistmodel',
            name='fit_completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fit_completed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fabricationlistmodel',
            name='received_completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_completed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fabricationlistmodel',
            name='shop_completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_completed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fabricationlistmodel',
            name='weld_completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weld_completed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
