# Generated by Django 5.2.1 on 2025-11-19 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fablist_app', '0007_fabricationlistmodel_clerk_completed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricationlistmodel',
            name='categories',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
